### ISSUE TITLE
*** 프로젝트 마감까지 필요한 작업 ***

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#101]
## Task
- 친구의 목표 리스트 뷰
  - [ ] 로직 구현
  - [ ] 로직 적용 및 UI 구조 작성
  - [ ] 디자인 적용 

- 전체 통계 뷰
  - [ ] 로직 구현
  - [ ] 로직 적용 및 UI 구조 작성
  - [ ] 디자인 적용 

- 늦은 인증글 작성 뷰 [S11]
  - [ ] 로직 구현
    - [x] #102
  - [ ] 로직 적용 및 UI 구조 작성
    - [x] #103
    - [x] #104
  - [ ] 디자인 적용 
    - [x] #105

- 목표별 페이지 뷰
  - [ ] 로직 구현
  - [ ] 로직 적용 및 UI 구조 작성
  - [ ] 디자인 적용 

- MainView [S12] [S14] 
  - [x] 로직 구현
    - #81
  - [ ] 로직 적용 및 UI 구조 작성
    - #87 
    - #96
    - #97
  - [ ] 디자인 적용 
    - [x] #106

- 실시간 진입 전 대기 화면 [S1] [S2]
  - [ ] 로직 구현
    - [x] #107
    - [x] #108
    - [x] #109
  - [ ] 로직 적용 및 UI 구조 작성
    - [x] #110
    - [x] #111
  - [ ] 디자인 적용
    - [x] #118
  
- LiveWritingView [S4]
  - [ ] 로직 구현
    - #68 
  - [ ] 로직 적용 및 UI 구조 작성
    - [x] #112
    - [x] #113
  - [ ] 디자인 적용 
    - [x] #114
  
- 목표 추가 뷰 [S19]
  - [ ] 로직 적용 및 UI 구조 작성
    - [x] #115
    - [x] #116
  - [ ] 디자인 적용
    - [x] #117

- MyPageView [S21]
  - [ ] 로직 적용 및 UI 구조 작성 (그래프 추가)
    - [x] #119
  - [ ] 디자인 적용
    - [x] #120

- SwipeView [S7]
  - [ ] 로직 적용 및 UI 구조 작성
    - [x] #121
  - [ ] 디자인 적용
    - [x] #122

- 친구리스트 뷰 [S17]
  - [ ] 로직 구현
    - #39 
    - #40 
    - #41 
  - [x] 로직 적용 및 UI 구조 작성
    - [x] #123
    - [x] #124
  - [ ] 디자인 적용
    - [x] #125

- [ ] 로컬 푸쉬알림
