### ISSUE TITLE
[S21] 마이페이지 뷰 UI 그래프에 데이터 가공해서 넣기

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#119]
## Task
**Related to User Story**: S21

## TODO
- [x] 그래프에 넣을 데이터 가공 방식 구상하기
- [x] 데이터 fetch 해와서 데이터 가공하기
- [x] 가공한 데이터 그래프에 전달해, 화면에 그려주기

## Expected Work Time
- 5시간
