### ISSUE TITLE
[S10]<-S12 실시간 인증 작성 후, 동적인 애니메이션의 형태로 반응을 확인할 수 있다

### ISSUE THREAD

**Issue by IamGroooooot** [cau-bootcamp/wehavit#12]
## Task
**User Story**: S10

### 선행되어야 하는 것
S12의 메인뷰가 필요

### 할 일

MainView에서 실시간 인증자의 경우, 격려를 받는 입장에서는 친구가 보낸 이모티콘이 풍선과 같은 형태로 떠오르는 등 

- [ ] 친구들이 나에게 남겨준 반응 가져오기

수신한 격려 보여주기
- [ ] 사진 반응 보여주기
- [ ] 이모지 반응 보여주기
- [ ] 텍스트 반응 보여주기

### 설명
실시간 인증 글 작성 후 친구들이 남겨준 반응을 MainView에서 확인할 수 있다.
이 반응은 사용자의 액션에 반응하는 동적인 에니메이션 형태로 보여진다.

### 결과물
- MainView로 오게 되면, 다른 친구들이 나의 실천 인증글에 남긴 반응이 인터렉티브 가능한 어떤 요소로 보인다. 그것에 대해 상호작용을 할 경우, 동적인 애니메이션 형태로 친구가 나에게 남긴 반응을 확인해 볼 수 있다.
