### ISSUE TITLE
[S11]<-S4 실시간 인증에 참석하지 못한 사용자는 MainView에서 애니메이션이 단조로운 형태로 인증글을 작성할 수 있다

### ISSUE THREAD

**Issue by IamGroooooot** [cau-bootcamp/wehavit#13]
## Task
**User Story**: S11

## 애니메이션과 시간 | 단조로워지는 조건
- 실시간 인증글을 작성해야만 애니메이션이 화려하게 한다면 로직이 복잡해진다.
- 따라서 애니메이션은 두 가지로 나뉘고, 특정 시간에만 화려한 애니메이션을 확인할 수 있게 만드는 것으로 한다.

### 선행 조건
우선 작업이 처리되어야 하는 스토리
 - #6 

### 할 일
- [ ] 오늘 인증을 남기지 못한 사용자는 다른 친구들의 인증 글을 확인할 수 없도록 가리는 기능 개발
- [ ] S4에서 만든 실시간 실천 인증 글 페이지에 다른 친구들이 작성한 글을 일부 가져와 띄워주는 기능 개발 
  - 상호작용은 안 된다
- [ ] 인증 글 피드(MainView)에서 늦은 인증 남기기 페이지로 이동하는 기능 개발
- [ ] 늦은 글 작성 기능 개발
  - 늦은 글 작성 뷰 개발
  - 글을 작성하고 나면 피드(MainView)로 이동한다
  - 이동 후, 친구들의 인증 글과 자신이 작성한 글이 피드(MainView)에 있는 것을 확인할 수 있다.

### 설명

실시간 인증을 남기지 못한 유저는 실천 인증 글 뷰에서 늦은 인증을 남길 수 있다.
늦은 인증 글 화면에서는 친구들과 반응을 주고받지 못하는 실시간 인증 화면에서 인증 글을 남기게 된다.
인증글을 남기면, 다른 친구들의 인증글에 대해 반응을 남길 수 있다.
