### ISSUE TITLE
[S12]<-S4,17 평소에 앱에 접속하는 사용자는 MainView를 통해 날짜별로 친구들의 실천 인증 글과 최근 인증 현황을 확인할 수 있다

### ISSUE THREAD

**Issue by IamGroooooot** [cau-bootcamp/wehavit#14]
## Task
**User Story**: S12

### 선행 조건
- #38
  - 친구 모델 필요
  - 친구 신청 필요
- #6 
  - 실천 인증 글 모델 필요
  - 기존의 인증 글을 불러올 수 있어야 함

---

### 할 일
 - [ ] MainView 레이아웃 개발
 - [ ] 날짜별로 친구들의 인증 글 불러오는 기능 개발
 - [ ] 친구들의 최근 인증 현황을 볼 수 있는 그래프 개발

### 설명
- MainView 개발
  - 날짜별로 친구들의 인증글이 보인다
  - 친구들의 최근 인증 현황을 확인할 수 있다

---

## 이 스토리에 의존하는 스토리
 - #16
