### ISSUE TITLE
[#21] 아키텍처 구조 반영 관련 공부

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#34]
## Task
**Related to User Story**: #21

### 예상되는 시간
4

### 설명
클린 아키텍처 구조를 적용하여, 뷰와 비즈니스 로직의 의존성을 떨어트리면서 로직을 적용해 기능을 구현하기 위해서 공부가 필요함.
- [x] 클린 아키텍처에 대한 공부
- [x] 상태 관리 Riverpod에 대한 공부
- [x] 이를 활용해 어떻게 뷰모델을 관리할 지에 대한 공부
