### ISSUE TITLE
[S7] 사진, 이모지, 텍스트 반응 전송 개발

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#51]
## Task
**Related to User Story** 
- #9 

### 설명
SwipeView 내 사진 반응 전송 기능을 구현한다.
SwipeView 내에서 친구의 인증글이 이모지를 반응으로 남길 수 있다.

### 선행 작업
- [x] S4의 인증글 데이터 구조가 나오면 반응을 전송하는 구조를 작성할 수 있음

### Todo
사진
- [x] 플러터에서 기기 카메라 권한 요청에 대한 정보 학습
- [x] 카메라 기능 접근, 카페라 촬영, 파일 형태로 앱으로 가져오기, 파일 포맷 지정에 대한 학습
- [x] 카메라 촬영 화면 및 제스처 기능 구현
- [x] 반응 전송 형식 설계 및 전송 기능 구현
  - ~요거는 인증글에 첨부하는 형식이라, 인증글 모델이 개발이 되고 나면 append 할 예정임~ 개발완료

이모지
- [x] 반응으로 주고받을 이모지 리스트 선정
- [x] 이모지 에셋 프로젝트에 추가하기
- [x] 이어서 반응 전송 설계에 따라 이모지 반응 전송 구현하기

텍스트
- [x] 반응 전송 형식에 맞춰 텍스트 전송 구현하기
