### ISSUE TITLE
[S10] 이미지 애니메이션 (풍선 효과) 구현하기

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#84]
## Task
**Related to User Story**: S10

### 설명
사용자가 친구의 인증글에 남긴 사진 반응을 애니메이션을 통해 확인할 수 있음.

## Todo
- [x] 이미지로 풍선처럼 화면을 떠다니도록 기능 구현
- [x] 떠다니는 풍선을 터치하면 터치는 이펙트가 나오면서 사라지도록 구현
- [x] 풍선을 터뜨릴 때 함수 재생할 수 있게 구조 작성
- [x] 쉽게 다른 뷰에서 사용할 수 있도록 정리 및 문서화하기
