### ISSUE TITLE
[S10] 인증글에 남겨진 격려를 애니메이션 효과로 보여주기

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#87]
## Task
**Related to User Story**: S10

### 설명
사용자가 친구의 인증글에 남긴 반응을 애니메이션을 통해 동적인 형태로 확인할 수 있음.

## 선행 작업
- #84 
- #86 

## Todo
- [x] 사용자의 인증글에서 반응 데이터들 받아오기
- [x] 텍스트 애니메이션 효과 연결하기
- [x] 이모지 애니메이션 효과 연결하기
- [x] 이미지 애니메이션 효과 연결하기

## 비고
메인뷰에 대한 작업이 딜레이됨에 따라, 
메인뷰에 이후에 쉽게 병합할 수 있게 별도의 위젯 형태로 개발을 진행한 뒤, StackView로 덮어씌워서 보여줄 수 있게 작업 진행할 예정
