### ISSUE TITLE
[S14] MainView의 버튼에 격려 전송 기능 연결

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#97]
## Task
**Related to User Story**: S14

### 설명
사용자가 MainView에서 친구의 인증글에 반응을 남길 수 있다.

## 선행 작업
- #51 
- 메인뷰 작성이 완료되어야함

## Todo
- [x] 텍스트 애니메이션 전송 기능 연결하기
- [x] 이모지 애니메이션 전송 기능 연결하기
- [x] 이미지 애니메이션 전송 기능 연결하기
